# Generated by Django 4.2.8 on 2023-12-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendance',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='attendancereport',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='feedbackfaculty',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='feedbackstudent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='leavereportfaculty',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='leavereportstudent',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='notificationfaculty',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='notificationstudent',
            managers=[
            ],
        ),
    ]
